---
- name: EKS Cluster _ K8s Master Node Configure + AWS CLI install
  hosts: eks_master

  vars_files:
    - aws_rootkey.yml

  tasks:
    - name: mkdir ~/bin
      file: ~/bin
      state: directory

    - name: get kubectl, aws-iam-authenticator
      get_url:
        url: "{{ item }}"
        dest: ~/bin
        mode: "0755"
      with_items:
        - { https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl }
        - { https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/aws-iam-authenticator }
          
    - name: export PATH
      command:
        argv:
          - export PATH=$HOME/bin:$PATH
          - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

    - name: get AWSCLIV2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: ~/awscliv2.zip

    - name: unarchive awscliv2.zip
      unarchive:
        src: ~/awscliv2.zip
        dest: ~/

    - name: aws cli install
      command: 
        argv:
          - sudo ~/aws/install
          - echo "Next Step - Configure Yourself
- aws configure
- aws eks update-kubeconfig --region [Region] --name [Cluster_Name]"
