---
- name: get kubectl, aws-iam-authenticator, aws_cli install
  hosts: eks_master

  tasks:
    - name: get kubectl, aws-iam-authenticator
      get_url:
        url: "{{ item }}"
        dest: /bin
        mode: "0755"
      with_items:
        - "https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl"
        - "https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/aws-iam-authenticator"

    - name: get AWSCLIV2
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: ~/awscliv2.zip

    - name: unzip install
      apt:
        name: unzip
        state: latest

    - name: unarchive awscliv2.zip
      unarchive:
        src: ~/awscliv2.zip
        dest: ~/
        remote_src: yes

    - name: aws cli install
      command: sudo ~/aws/install
